GOOGLE_PRO_API_KEY_1 = "AIzaSyA6ibuxwntCMyX_y1iFU8PdY9b8Zgy1cjo"
GOOGLE_PRO_API_KEY_2 = "AIzaSyAx4LCZFB3NOD9dUuRiA7_vepp-tTG4EKw"
GOOGLE_PRO_API_KEY_3 = "AIzaSyBrMdel1QDLuzrLPSxZr1yHWWOxq5lD7Rk"
GOOGLE_DEV_API_KEY_1 = "AIzaSyBj2uOP4n4JTYA6kfUeQZSxLx_nEJ_7iik"
BANXICO_API_KEY = "0ef3441d84aa0a0f7ad00b749c938ae4ecd09ef154c649f478efd9a9787f57b7"